services:
  - type: web
    name: mansion-bot-backend
    runtime: node
    buildCommand: apt-get update && apt-get install -y chromium-browser && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
